### ISSUE TITLE
Publish v1.0.0

### ISSUE THREAD

**Issue by bisejdiu** [ProLint/prolint2#80]
Once #78 has been merged into the main branch, we can upgrade the package version to 1.0, which will be a significant achievement. However, there is still a long way to go. We require extensive (1) testing and (2) the addition of tutorial/example notebooks.

**Comment by danielpastor97** [comment]
The current version (improved syntax and performance) is already merged in the main branch. Before releasing the version 1.0.0 I will tackle the following points:
- [ ] Updating/re-adding interactive selection and contact export functionalities.
- [ ] Rewriting the tests with the new API.
- [ ] Update/Fix/Change the macro interface.
- [ ]  Add PL2Plotter class.
